### ISSUE TITLE
[Bug] - Analyzer fails to forward RQA

### ISSUE THREAD

**Issue by franksn90** [dqualizer/dqanalyzer#29]
## Describe the bug

Since PR#25, using the docker compose file from https://github.com/dqualizer/dqualizer, the modeler does not forward the RQA.

## To Reproduce

1. Open the modeler
2. Specify RQA
3. Press Execute
4. (nothing happens)

## Expected behavior

I expect results on the Grafana board or at least log messages of the executed RQA on the console.

## Additional information (screenshots, stack traces, etc.)

On PR#24:
![Screenshot 2023-05-05 at 09 55 59](https://user-images.githubusercontent.com/18191871/236408509-b31156ce-f512-4702-9447-c7c5f7f387de.png)

On PR#25 / latest:
![Screenshot 2023-05-05 at 09 43 59](https://user-images.githubusercontent.com/18191871/236408513-ad040673-9f4d-4093-94d5-fecae8bbbbb4.png)

## Desktop (please complete the following information):

- OS: macOS
- Browser: Firefox
- Version: 111.01

## Additional context

According to the screenshots, RQAs are now sent to different addresses (localhost:8070 vs localhost:8080). I suggest to have a look at the default "VITE_BACKEND_URL" environment variable of the modeler container. As a quick fix, changing it in the docker compose file (as shown below) seems to solve the issue, but changes to the dqanalyzer component might be necessary as well.

```
  dqanalyzer-frontend:
    image: ghcr.io/dqualizer/dqanalyzer-frontend
    ports:
      - "9080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8070
```
